---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  linebreak-style: off
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]