export default (i18next) => {
  document.querySelector('[data-text="example_name"]')
    .textContent = i18next.t('example.name');

  document.querySelector('[data-text="example_title_1"]')
    .textContent = i18next.t('example.title_1');

  document.querySelector('[data-text="example_subtitle_1"]')
    .textContent = i18next.t('example.subtitle_1');
  document.querySelector('[data-text="example_subtitle_2"]')
    .textContent = i18next.t('example.subtitle_2');
  document.querySelector('[data-text="example_subtitle_3"]')
    .textContent = i18next.t('example.subtitle_3');
  document.querySelector('[data-text="example_subtitle_4"]')
    .textContent = i18next.t('example.subtitle_4');
  document.querySelector('[data-text="example_subtitle_5"]')
    .textContent = i18next.t('example.subtitle_5');
  document.querySelector('[data-text="example_subtitle_6"]')
    .textContent = i18next.t('example.subtitle_6');
  document.querySelector('[data-text="example_subtitle_7"]')
    .textContent = i18next.t('example.subtitle_7');
  document.querySelector('[data-text="example_subtitle_8"]')
    .textContent = i18next.t('example.subtitle_8');
  document.querySelector('[data-text="example_subtitle_9"]')
    .textContent = i18next.t('example.subtitle_9');
  document.querySelector('[data-text="example_subtitle_10"]')
    .textContent = i18next.t('example.subtitle_10');

  document.querySelector('[data-text="example_p_1"]')
    .textContent = i18next.t('example.p_1');
  document.querySelector('[data-text="example_p_2"]')
    .textContent = i18next.t('example.p_2');
  document.querySelector('[data-text="example_p_3"]')
    .textContent = i18next.t('example.p_3');
  document.querySelector('[data-text="example_p_4"]')
    .textContent = i18next.t('example.p_4');
  document.querySelector('[data-text="example_p_5"]')
    .textContent = i18next.t('example.p_5');
  document.querySelector('[data-text="example_p_6"]')
    .textContent = i18next.t('example.p_6');
  document.querySelector('[data-text="example_p_7"]')
    .textContent = i18next.t('example.p_7');
  document.querySelector('[data-text="example_p_8"]')
    .textContent = i18next.t('example.p_8');
  document.querySelector('[data-text="example_p_9"]')
    .textContent = i18next.t('example.p_9');
  document.querySelector('[data-text="example_p_10"]')
    .textContent = i18next.t('example.p_10');
  document.querySelector('[data-text="example_p_11"]')
    .textContent = i18next.t('example.p_11');
  document.querySelector('[data-text="example_p_12"]')
    .textContent = i18next.t('example.p_12');
  document.querySelector('[data-text="example_p_13"]')
    .textContent = i18next.t('example.p_13');
  document.querySelector('[data-text="example_p_14"]')
    .textContent = i18next.t('example.p_14');
  document.querySelector('[data-text="example_p_15"]')
    .textContent = i18next.t('example.p_15');
  document.querySelector('[data-text="example_p_16"]')
    .textContent = i18next.t('example.p_16');
  document.querySelector('[data-text="example_p_17"]')
    .textContent = i18next.t('example.p_17');
  document.querySelector('[data-text="example_p_18"]')
    .textContent = i18next.t('example.p_18');
  document.querySelector('[data-text="example_p_19"]')
    .textContent = i18next.t('example.p_19');
  document.querySelector('[data-text="example_p_20"]')
    .textContent = i18next.t('example.p_20');
  document.querySelector('[data-text="example_p_21"]')
    .textContent = i18next.t('example.p_21');
  document.querySelector('[data-text="example_p_22"]')
    .textContent = i18next.t('example.p_22');
  document.querySelector('[data-text="example_p_23"]')
    .textContent = i18next.t('example.p_23');

  document.querySelector('[data-text="example_li_1"]')
    .textContent = i18next.t('example.li_1');
  document.querySelector('[data-text="example_li_2"]')
    .textContent = i18next.t('example.li_2');
  document.querySelector('[data-text="example_li_3"]')
    .textContent = i18next.t('example.li_3');
  document.querySelector('[data-text="example_li_4"]')
    .textContent = i18next.t('example.li_4');
};
